Check that $row is not a string or array
UseMuffin/Crypt pull request #6
Opened 2017-05-01 17:19 UTC by shoesole

Bypass the $row->has() test in the case that the $row is actually a string or an array. The rules checker ExistsIn method will return the row as an array, the “list” finder will return the $row as a string. Both will return a fatal error when $row->has() is called in the Crypt Behavior.

2017-05-01 18:06 UTC, ADmad requested changes

2017-05-01 18:06 UTC, ADmad commented on src/Model/Behavior/CryptBehavior.php
> +                    || is_string($row) || (is_array($row) ? !isset($row[$field]) : !$row->has($field))
This can be simplified to ` || !($row instanceof EntityInterface) || !$row->has($field)`

2017-05-01 18:25 UTC, shoesole commented
Great point. I just tested that against both cases I had that were failing (both a find->('list') and a save with a related model triggering an ExistsIn and it worked perfectly. I just made another commit.

2017-05-01 18:35 UTC, ADmad commented
Nice, now just need a test case to avoid regression in future.

2017-05-01 18:50 UTC, chrisShick reviewed
Shouldn't we check if $query->isHydrationEnabled() before any of this? Why add the formatter at all if it isn't enabled?

2017-05-01 18:51 UTC, chrisShick commented on src/Model/Behavior/CryptBehavior.php
> +                    || is_string($row) || (is_array($row) ? !isset($row[$field]) : !$row->has($field))
Shouldn't we check if $query->isHydrationEnabled() before any of this? Why add the formatter at all if it isn't enabled? ( I meant to add the comment here)

2017-05-01 19:03 UTC, ADmad commented
@chrisShick That could be an optimization, just return `$query` instance early if hydration is disabled.

2017-05-01 19:13 UTC, chrisShick commented
That is what I was thinking. I implemented it in https://github.com/UseMuffin/Crypt/pull/5.

Also, should the mapper even be added if the resultSet->isEmpty() returns true?

2017-05-01 19:22 UTC, ADmad commented
You cannot know whether result set in empty until query is executed and calling `->isEmpty()` would prematurely execute the query. Finder should only return modified query object not actually execute the query.

2017-05-01 19:25 UTC, chrisShick commented
You could check inside the formatter for `$resultSet->isEmpty() ` and return the results instead of adding the mapper.

2017-05-01 19:33 UTC, ADmad commented
Such a micro optimization isn't really necessary and just adds an unnecessary check for majority case where results are present.

2017-05-08 19:48 UTC, chrisShick commented
Any plans to merge this?

2017-05-08 19:51 UTC, ADmad commented
As mentioned earlier test case is needed for the fix.

2017-05-09 19:17 UTC, chrisShick commented
For the test case, wouldn't we have to add a model in order to put the build rule in and another fixture for customers?

2017-09-13 08:56 UTC, merged